name: probe

services:
  gatherer:
    image: sinytra/probe/gatherer:latest
    command: regressions --results=/probe/old_results.json
    volumes:
      - ./gatherer/run:/probe
    environment:
      - REDIS_URL=redis://probe-cache-1:6379/0
      - TEST_COUNT=10
    networks:
      - probe
  postgres:
    image: postgres:16.2
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=probe
      - POSTGRES_USER=probe
      - POSTGRES_DB=probe
    networks:
      - probe
  cache:
    image: redis:8.0-rc1
    ports:
      - "6379:6379"
    networks:
      - probe
networks:
  probe:
volumes:
  db:
