name: probe

services:
  postgres:
    image: postgres:16.2
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=probe
      - POSTGRES_USER=probe
      - POSTGRES_DB=probe
    networks:
      - probe
networks:
  probe:
volumes:
  db:
