name: Perform tests

on:
  workflow_dispatch: 

jobs:
  run_tests:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name probe_redis
        ports:
          - 6379:6379

    permissions:
      packages: read

    steps:
      - name: Setup env
        run: mkdir probe
      - uses: tespkg/actions-cache@v1
        with:
          accessKey: ${{ secrets.S3_ACCESS_KEY }}
          secretKey: ${{ secrets.S3_SECRET_KEY }}
          bucket: ${{ secrets.S3_BUCKET_NAME }}
          use-fallback: false

          key: ${{ runner.os }}-mods-${{ hashFiles('probe/candidates.json') }}
          path: |
            probe/.setup
            probe/mods
            probe/candidates.json
            probe/dump.rdb
          restore-keys: |
            ${{ runner.os }}-mods-
      - if: ${{ hashFiles('probe/dump.rdb') != '' }}
        run: |
          docker stop probe_redis
          docker cp probe/dump.rdb probe_redis:/data/dump.rdb
          docker start probe_redis
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run tests in a container
        run: >
          docker run --rm
          --network host
          -v ./probe:/probe
          -e REDIS_URL=redis://localhost:6379/0
          -e TEST_COUNT=20
          ghcr.io/sinytra/probe/gatherer:latest