name: Release Gatherer

on:
  workflow_dispatch:

env:
  IMAGE: ghcr.io/sinytra/probe/gatherer

jobs:
  build:
    name: Build and push docker

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build and Push Image
        env:
          DOCKER_REG_USERNAME: ${{ github.actor }}
          DOCKER_REG_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew :gatherer:jib
