name: Release

on:
  push:
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_REG_USERNAME: ${{ github.actor }}
  DOCKER_REG_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build and push ${{ matrix.project }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        project: [ gatherer, discord, service ]

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build and Push Image
        run: ./gradlew build :${{ matrix.project }}:jib
